MySQL:
  SSL: False
  Host: "localhost"
  Port: "3306"
  Database: "database"
  User: "root"
  Password: ""

Maintenance: False
Permission: bansystem.maintenance
Message: "&d&lCandyCraft&8.&dde\n\n&8» &cDer Server befindet sich in &4Wartungsarbeiten&c."
